//The contents of this file was removed due to copyright restrictions
//Original file size: 105358 bytes
//Originally declared classes/interfaces/structs:
//class CrossParamsObject
//class ComboBoxValue
//class ExpressionStatement
//class CrossAngle : CrossParamsObject
//class AProfile : CrossParamsObject
//class AProfile10MRake : CrossParamsObject
//class AProfile10MRakeLeft : CrossParamsObject
//class AProfile10MRakeRight : CrossParamsObject
//class AProfileHorL : CrossParamsObject
//class AProfileHorLLeft : CrossParamsObject
//class AProfileHorLRight : CrossParamsObject
//class RProfileRake : CrossParamsObject
//class RProfileRakeLeft : CrossParamsObject
//class RProfileRakeRight : CrossParamsObject
//class AProfile20MRake : CrossParamsObject
//class AProfile20MRakeLeft : CrossParamsObject
//class AProfile20MRakeRight : CrossParamsObject
//class AVisibility : CrossParamsObject
//class AVisibilityLeft : CrossParamsObject
//class AVisibilityLeftSideOddR : CrossParamsObject
//class AVisibilityLeftSideEvenR : CrossParamsObject
//class AVisibilityRight : CrossParamsObject
//class AVisibilityRightSideOddR : CrossParamsObject
//class AVisibilityRightSideEvenR : CrossParamsObject
//class RVisibility : CrossParamsObject
//class RVisibilityOddR : CrossParamsObject
//class RVisibilityEvenR : CrossParamsObject
//class CrossWidth : CrossParamsObject
//class CrossLength : CrossParamsObject
//class CrossCattleWidth : CrossParamsObject
//class IsFootway : CrossParamsObject
//class FloorMaterial : CrossParamsObject
//class ARoadMaterial : CrossParamsObject
//class DirColFarDistance : CrossParamsObject
//class DirColFarDistanceLeft : CrossParamsObject
//class DirColFarDistanceRight : CrossParamsObject
//class Material : CrossParamsObject
//class DirColMaterial : CrossParamsObject
//class RailingMaterial : CrossParamsObject
//class GuardMaterial : CrossParamsObject
//class ToArEdgeDistance : CrossParamsObject
//class DirColToArEdgeDistance : CrossParamsObject
//class RailingToArEdgeDistance : CrossParamsObject
//class GuardToArEdgeDistance : CrossParamsObject
//class RoadSign : CrossParamsObject
//class RoadSignWithBarrierCount : CrossParamsObject
//class RoadSignWithNoBarrierCount : CrossParamsObject
//class RoadSignRailWayCount : CrossParamsObject
//class RoadSignApproachingCount : CrossParamsObject
//class RoadSignStopCount : CrossParamsObject
//class RoadSignHeightLimitCount : CrossParamsObject
//class SignSCount : CrossParamsObject
//class SignSDistance : CrossParamsObject
//class ReserveBarrierCount : CrossParamsObject
//class IsBlockingAlarm : CrossParamsObject
//class BlockTrlig : CrossParamsObject
//class BlockTrlig1Distance : CrossParamsObject
//class BlockTrlig2Distance : CrossParamsObject
//class BlockTrlig3Distance : CrossParamsObject
//class BlockTrlig4Distance : CrossParamsObject
//class IsAdditionalAlarm : CrossParamsObject
//class Comm : CrossParamsObject
//class IsPhoneComm : CrossParamsObject
//class IsRadioComm : CrossParamsObject
//class CrossKind : CrossParamsObject
//class CrossType : CrossParamsObject
//class BarrierEngType : CrossParamsObject
//class BarrierGeomType : CrossParamsObject
//class AlarmType : CrossParamsObject
//class IsAlarmServiceControl : CrossParamsObject
//class OtherDevice : CrossParamsObject
//class IsFloodLight : CrossParamsObject
//class Light : CrossParamsObject
//class LightCategory : CrossParamsObject
//class LightLevel : CrossParamsObject
//class WireHeight : CrossParamsObject
//class ContactWireHeight : CrossParamsObject
//class PowerWireHeight : CrossParamsObject
//class IsBottomSizeChecker : CrossParamsObject
//class IsHorizontalMarkup : CrossParamsObject
//class Floor : CrossParamsObject
//class FloorHeight : CrossParamsObject
//class FloorMinHeightOutsideRails : CrossParamsObject
//class FloorMaxHeightOutsideRails : CrossParamsObject
//class FloorMinHeightInsideRails : CrossParamsObject
//class FloorMaxHeightInsideRails : CrossParamsObject
//class ContrRail : CrossParamsObject
//class IsContrRail : CrossParamsObject
//class ContrRailBendInside : CrossParamsObject
//class ContrRailGutterWidth : CrossParamsObject
//class ContrRailGutterDepth : CrossParamsObject
//class BlockingDevice : CrossParamsObject
//class IsBlockingDevice : CrossParamsObject
//class IsBlockingDeviceWholeOverlays : CrossParamsObject
//class BlockingDeviceHeight : CrossParamsObject
//class IsSizeFrame : CrossParamsObject
