//The contents of this file was removed due to copyright restrictions
//Original file size: 25097 bytes
//Originally declared classes/interfaces/structs:
//interface IAsupIsso
//interface IAsupNormIntertrack
//interface IAsupPrz
//interface IAsupPutgl
//interface IAsupWayPlan
//interface IAsupZdan
//interface IAsupDor
//interface IAsupPutglDor
//interface IAsupPutglPeregon
//interface IAsupStan
//interface IVolume
//interface IMeasure
//interface IGeoradarValue
//interface IGeoradarImage
//interface IDocument
//interface ISurvey : IStationingRange
//interface IDocumentToSurvey
//interface IAsupDist
//interface IExpLog
//interface IImpLog
//interface IImpLogItem
//interface ISurveyFull : ISurvey
//interface ILsData
//interface IStationingCacheAxisInfo
//interface IStationingCachePicketInfo
//interface ITask
//interface ITaskStep
//interface ITaskFeature
//interface ITaskCheck
//interface ITaskCheckViolation
//interface IDocumentToTask
//interface ISurveyToTask
//interface ISurveyToTask2
//interface ITaskData
//interface ISurveyLsData
//interface ISurveyMeasure
//interface ISurveyDocument
//interface ISurveyGeoradarData
//interface ISurveyGeoradarImage
//interface IStationingCacheAxisBoundary
//interface ICalc
//interface ICalcData
//interface ICalcAttr
//interface ICalcValue
//interface ICalcChart
//interface ICalcMessage
//interface IAxisDataPlan
//interface IAxisDataRake
//interface IAxisDataRailElevation
//interface ICalcObject
//interface ISurveySurfaceData
//interface ISurfaceData
//interface IGeoradarData
//interface IAsupPutglUp
//interface IDocumentToCalc
//interface IMapFragmentAxisLine
//interface IMapFragmentAxisToDrmAlign
//interface IStationingCacheKmLength
//interface IStationingCachePkLength
//interface IStationingCacheWaypartRange
//interface IPeregon
//interface IStationingRange
//interface IMapFragmentVersion
//interface IFraction
//interface IStationingCacheObjectPos
//interface IExpLogItem
