//The contents of this file was removed due to copyright restrictions
//Original file size: 2063952 bytes
//Originally declared classes/interfaces/structs:
//class LandXML
//class Alignments
//class Alignment
//class ConnSpiral
//class Spiral
//class PointType
//class RawObservationType
//class OffsetVals
//class Feature
//class Property
//class DocFileRef
//class FieldNote
//class PointType3dReq
//class Curve1
//class Curve
//class Curve2
//class InSpiral
//class OutSpiral
//class Cant
//class CantStation
//class SpeedStation
//class CoordGeom
//class Line
//class CrossSect
//class CrossSectSurf
//class DesignCrossSectSurf
//class CrossSectPnt : PointType
//class Profile
//class ProfAlign
//class CircCurve
//class PVI
//class ParaCurve
//class UnsymParaCurve
//class ProfSurf
//class Amendment
//class AmendmentItem
//class Application
//class Author
//class CgPoints
//class CgPoint : PointType
//class CoordinateSystem
//class FeatureDictionary
//class GradeModel
//class GradeSurface
//class Zones
//class Zone
//class ZoneCrossSectStructure
//class ZoneCutFill
//class ZoneMaterial
//class ZoneSlope
//class ZoneWidth
//class ZoneHinge
//class Monuments
//class Monument
//class Parcels
//class Parcel
//class Exclusions
//class LocationAddress
//class ComplexName
//class RoadName
//class AdministrativeArea
//class AddressPoint : PointType
//class Title
//class VolumeGeom
//class PipeNetworks
//class PipeNetwork
//class Structs
//class Units
//class Imperial
//class Metric
//class Struct
//class CircStruct
//class Connection
//class InletStruct
//class OutletStruct
//class RectStruct
//class Invert
//class StructFlow
//class Pipes
//class Pipe
//class Channel
//class CircPipe
//class EggPipe
//class ElliPipe
//class RectPipe
//class PipeFlow
//class PlanFeatures
//class PlanFeature
//class Project
//class Intersections
//class Intersection
//class Corner
//class Curb
//class Timing
//class TrafficControl
//class TurnRestriction
//class TurnSpeed
//class Volume
//class BridgeElement
//class Classification
//class CrashData
//class CrashHistory
//class DecisionSightDistance
//class Lanes
//class ClimbLane
//class OffsetLane
//class PassingLane
//class ThruLane
//class TurnLane
//class TwoWayLeftTurnLane
//class WideningLane
//class NoPassingZone
//class Roadside
//class BikeFacilities
//class Ditch
//class DrivewayDensity
//class HazardRating
//class ObstructionOffset
//class RoadSign
//class Speeds
//class DesignSpeed
//class DesignSpeed85th
//class PostedSpeed
//class TrafficVolume
//class DailyTrafficVolume
//class DesignHour
//class PeakHour
//class Definition
//class P : PointType
//class Faces
//class F
//class SourceData
//class Boundaries
//class Boundary
//class Breaklines
//class Breakline
//class RetWall
//class RetWallPnt : PointType3dReq
//class Contours
//class Contour
//class DataPoints
//class PointFiles
//class PointFile
//class Watersheds
//class Watershed
//class Outlet : PointType3dReq
//class SurfVolumes
//class SurfVolume
//class Survey
//class SurveyHeader
//class AdministrativeDate
//class Annotation
//class HeadOfPower
//class Personnel
//class PurposeOfSurvey
//class SurveyorCertificate
//class Equipment
//class GPSAntennaDetails
//class GPSReceiverDetails
//class InstrumentDetails
//class Corrections
//class LaserDetails
//class ControlChecks
//class ObservationGroup
//class Backsight
//class RawObservation : RawObservationType
//class RedHorizontalPosition
//class RedVerticalObservation
//class ReducedArcObservation
//class ReducedObservation
//class PointResults
//class TestObservation : RawObservationType
//class GPSPosition
//class GPSQCInfoLevel1
//class GPSQCInfoLevel2
//class GPSSetup
//class TargetSetup
//class GPSVector
//class InstrumentSetup
//class LaserSetup
//class SurveyMonument
//class Pnts
//class AlignPI
