//The contents of this file was removed due to copyright restrictions
//Original file size: 12563 bytes
//Originally declared classes/interfaces/structs:
//interface IAlign
//interface IAlignElement
//interface IAlignPoint
//interface IAlignPointMath
//interface IBlockStation
//interface ICdProf
//interface ICurveDef
//interface IFootBridge
//interface IGradeProf
//interface IHut
//interface IInsulatedJoint
//interface INaturalGroundPoint
//interface IObjectAttribute
//interface IObjectType
//interface IPassingTrackSection
//interface IPipe
//interface IPlanTask
//interface IPointObjectAttrValue
//interface IPointObjectOld
//interface IPrj
//interface IProfileTask
//interface IRailwayCrossing
//interface ISta
//interface IStation
//interface IStationIrr
//interface IStationMath
//interface IStopPoint
//interface ISubgradeEdge
//interface ISwitch
//interface ITower
//interface ITowerClearance
//interface ITrafficLight
//interface ITrafficLightClearance
//interface IBridge
//interface IBridgeSpan
//interface IBuilding
//interface ICableLine
//interface IDerailingShoe
//interface IFoulingIndicator
//interface IPipeline
//interface IPlatform
//interface IPlatformPoint
//interface IRoadCrosspass
//interface ISpeed
//interface IStoppingDevice
//interface IAlignPointOpStationing
//interface IAlignElementOp
//interface IAlignOp
//interface IAlignPointOp
//interface IGradeProfOp
//interface IAlignElementAp
//interface IAlignElementApPp
//interface IAlignElementOpPp
//interface IStationIrrKmInfo
//interface IStationIrrPkInfo
//interface IGradeProfAp
//interface IGradeProfApPp
//interface IGradeProfOpPp
//interface ICurveDefPair
//interface ICurveDefPair2
//interface IStationingCachePropRange
//interface IStationingCacheSpeedRange
