//The contents of this file was removed due to copyright restrictions
//Original file size: 109813 bytes
//Originally declared classes/interfaces/structs:
//class GDB
//class Tables
//class FeatureClasses
//class AxisLine : GDB.Common.fcPrimary
//class ContactNetworkSupportPoint : GDB.Common.fcPrimary
//class PicketColumnPoint : GDB.Common.fcPrimary
//class StationingPoint : GDB.Common.fcPrimaryStationing
//class RailThreadLine : GDB.Common.fcPrimary
//class AxesOverlayLine : GDB.Common.fcPrimary
//class TrafficLightPoint : GDB.Common.fcPrimary
//class RailroadAndPedestrianCrossingArea : GDB.Common.fcPrimary
//class TieAxisLine : GDB.Common.fcPrimary
//class HydrographyLine : GDB.Common.fcPrimary
//class SettlementStructureArea : GDB.Common.fcPrimary
//class FenceLine : GDB.Common.fcPrimary
//class LightingPoint : GDB.Common.fcPrimary
//class CarrierWireLine : GDB.Common.fcPrimary
//class RoadLine : GDB.Common.fcPrimary
//class PowerLine : GDB.Common.fcPrimary
//class PlatformArea : GDB.Common.fcPrimary
//class ContactWireLine : GDB.Common.fcPrimary
//class LimitColumnPoint : GDB.Common.fcPrimary
//class ContactNetworkTrussSupportLine : GDB.Common.fcPrimary
//class ISSOArea : GDB.Common.fcPrimary
//class SurfaceMarkPoint : GDB.Common.fcPrimary
//class PointOfInterestPoint : GDB.Common.fcPrimary
//class FixedStationing : GDB.Common.fcPrimaryStationing
//class StationCenterPoint : GDB.Common.fcPrimary
//class SettlementStructure3D : GDB.Common.fcPrimary
//class Lighting3D : GDB.Common.fcPrimary
//class GroundPowerSupplyObject3D : GDB.Common.fcPrimary
//class FundamOfSupportAndAnchor3D : GDB.Common.fcPrimary
//class TrackSwitchPoint : GDB.Common.fcPrimary
//class PicketColumnPoint3D : GDB.Common.fcPrimary
//class Platform3D : GDB.Common.fcPrimary
//class TrafficLight3D : GDB.Common.fcPrimary
//class ContactNetworkSupport3D : GDB.Common.fcPrimary
//class BridgeSpanArea : GDB.Common.fcPrimary
//class EquipmentRailwayCrossing3D : GDB.Common.fcPrimary
//class ISSO3D : GDB.Common.fcPrimary
//class PassengerInfrastructure3D : GDB.Common.fcPrimary
//class TrackStop3D : GDB.Common.fcPrimary
//class LimitColumn3D : GDB.Common.fcPrimary
//class Mark3D : GDB.Common.fcPrimary
//class SignalOrGuideColumn3D : GDB.Common.fcPrimary
//class Speaker3D : GDB.Common.fcPrimary
//class Fence3D : GDB.Common.fcPrimary
//class TrackStopPoint : GDB.Common.fcPrimary
//class StructuralLine : GDB.Common.fcPrimary
//class FundamOfSupportAndAnchorLine : GDB.Common.fcPrimary
//class TrafficLightLine : GDB.Common.fcPrimary
//class ContactNetworkTrussSupportArea : GDB.Common.fcPrimary
//class TrafficLightArea : GDB.Common.fcPrimary
//class GroundPowerSupplyObjectArea : GDB.Common.fcPrimary
//class StationObjectPoint : GDB.Common.fcPrimary
//class IsolatingJunctionPoint : GDB.Common.fcPrimary
//class SignalOrGuideColumnPoint : GDB.Common.fcPrimary
//class VegetationContourArea : GDB.Common.fcPrimary
//class RoadArea : GDB.Common.fcPrimary
//class HillArea : GDB.Common.fcPrimary
//class WagonWeigherPoint : GDB.Common.fcPrimary
//class TrainShoeKickerPoint : GDB.Common.fcPrimary
//class WagonStopPoint : GDB.Common.fcPrimary
//class MarkPoint : GDB.Common.fcPrimary
//class LightingFarmLine : GDB.Common.fcPrimary
//class EquipmentRailwayCrossingPoint : GDB.Common.fcPrimary
//class SpeakerPoint : GDB.Common.fcPrimary
//class HorizontalLine : GDB.Common.fcPrimary
//class ZoneArea : GDB.Common.fcPrimary
//class ThroughMeterPicketPoint : GDB.Common.fcPrimary
//class ContourHydrographyArea : GDB.Common.fcPrimary
//class AuxiliaryAxisLine : GDB.Common.fcPrimary
//class DatumMarkPoint : GDB.Common.fcPrimary
